package gameboy.emulator.processor;

import java.util.HashMap;

// Allows converting an opcode into a String instruction for debugging purposes.
// This also includes fake opcodes for halts and interrupts.
public class Decoder {
    public final static HashMap<Integer, String> OPCODE_MAP = createOpcodeMap();

    public static String decodeOpcode(int opcode) {
        return OPCODE_MAP.get(opcode);
    }

    public static HashMap<Integer, String> createOpcodeMap() {
        HashMap<Integer, String> opcodeMap = new HashMap<>();

        opcodeMap.put(-1, "[HALTING]");

        opcodeMap.put(800, "<(CANCELLED)>");
        opcodeMap.put(900, "<VBLANK>");
        opcodeMap.put(901, "<STAT>");
        opcodeMap.put(902, "<TIMER>");
        opcodeMap.put(903, "<SERIAL>");
        opcodeMap.put(904, "<JOYPAD>");

        opcodeMap.put(0x00, "NOP");
        opcodeMap.put(0x01, "LD BC, d16");
        opcodeMap.put(0x02, "LD (BC), A");
        opcodeMap.put(0x03, "INC BC");
        opcodeMap.put(0x04, "INC B");
        opcodeMap.put(0x05, "DEC B");
        opcodeMap.put(0x06, "LD B, d8");
        opcodeMap.put(0x07, "RLCA");
        opcodeMap.put(0x08, "LD (a16), SP");
        opcodeMap.put(0x09, "ADD HL, BC");
        opcodeMap.put(0x0A, "LD A, (BC)");
        opcodeMap.put(0x0B, "DEC BC");
        opcodeMap.put(0x0C, "INC C");
        opcodeMap.put(0x0D, "DEC C");
        opcodeMap.put(0x0E, "LD C, d8");
        opcodeMap.put(0x0F, "RRCA");

        opcodeMap.put(0x10, "STOP");
        opcodeMap.put(0x11, "LD DE, d16");
        opcodeMap.put(0x12, "LD (DE), A");
        opcodeMap.put(0x13, "INC DE");
        opcodeMap.put(0x14, "INC D");
        opcodeMap.put(0x15, "DEC D");
        opcodeMap.put(0x16, "LD D, d8");
        opcodeMap.put(0x17, "RLA");
        opcodeMap.put(0x18, "JR s8");
        opcodeMap.put(0x19, "ADD HL, DE");
        opcodeMap.put(0x1A, "LD A, (DE)");
        opcodeMap.put(0x1B, "DEC DE");
        opcodeMap.put(0x1C, "INC E");
        opcodeMap.put(0x1D, "DEC E");
        opcodeMap.put(0x1E, "LD E, d8");
        opcodeMap.put(0x1F, "RRA");

        opcodeMap.put(0x20, "JR NZ, s8");
        opcodeMap.put(0x21, "LD HL, d16");
        opcodeMap.put(0x22, "LD (HL+), A");
        opcodeMap.put(0x23, "INC HL");
        opcodeMap.put(0x24, "INC H");
        opcodeMap.put(0x25, "DEC H");
        opcodeMap.put(0x26, "LD H, d8");
        opcodeMap.put(0x27, "DAA");
        opcodeMap.put(0x28, "JR Z, s8");
        opcodeMap.put(0x29, "ADD HL, HL");
        opcodeMap.put(0x2A, "LD A, (HL+)");
        opcodeMap.put(0x2B, "DEC HL");
        opcodeMap.put(0x2C, "INC L");
        opcodeMap.put(0x2D, "DEC L");
        opcodeMap.put(0x2E, "LD L, d8");
        opcodeMap.put(0x2F, "CPL");

        opcodeMap.put(0x30, "JR NC, s8");
        opcodeMap.put(0x31, "LD SP, d16");
        opcodeMap.put(0x32, "LD (HL-), A");
        opcodeMap.put(0x33, "INC SP");
        opcodeMap.put(0x34, "INC (HL)");
        opcodeMap.put(0x35, "DEC (HL)");
        opcodeMap.put(0x36, "LD (HL), d8");
        opcodeMap.put(0x37, "SCF");
        opcodeMap.put(0x38, "JR C, s8");
        opcodeMap.put(0x39, "ADD HL, SP");
        opcodeMap.put(0x3A, "LD A, (HL-)");
        opcodeMap.put(0x3B, "DEC SP");
        opcodeMap.put(0x3C, "INC A");
        opcodeMap.put(0x3D, "DEC A");
        opcodeMap.put(0x3E, "LD A, d8");
        opcodeMap.put(0x3F, "CCF");

        opcodeMap.put(0x40, "LD B, B");
        opcodeMap.put(0x41, "LD B, C");
        opcodeMap.put(0x42, "LD B, D");
        opcodeMap.put(0x43, "LD B, E");
        opcodeMap.put(0x44, "LD B, H");
        opcodeMap.put(0x45, "LD B, L");
        opcodeMap.put(0x46, "LD B, (HL)");
        opcodeMap.put(0x47, "LD B, A");
        opcodeMap.put(0x48, "LD C, B");
        opcodeMap.put(0x49, "LD C, C");
        opcodeMap.put(0x4A, "LD C, D");
        opcodeMap.put(0x4B, "LD C, E");
        opcodeMap.put(0x4C, "LD C, H");
        opcodeMap.put(0x4D, "LD C, L");
        opcodeMap.put(0x4E, "LD C, (HL)");
        opcodeMap.put(0x4F, "LD C, A");

        opcodeMap.put(0x50, "LD D, B");
        opcodeMap.put(0x51, "LD D, C");
        opcodeMap.put(0x52, "LD D, D");
        opcodeMap.put(0x53, "LD D, E");
        opcodeMap.put(0x54, "LD D, H");
        opcodeMap.put(0x55, "LD D, L");
        opcodeMap.put(0x56, "LD D, (HL)");
        opcodeMap.put(0x57, "LD D, A");
        opcodeMap.put(0x58, "LD E, B");
        opcodeMap.put(0x59, "LD E, C");
        opcodeMap.put(0x5A, "LD E, D");
        opcodeMap.put(0x5B, "LD E, E");
        opcodeMap.put(0x5C, "LD E, H");
        opcodeMap.put(0x5D, "LD E, L");
        opcodeMap.put(0x5E, "LD E, (HL)");
        opcodeMap.put(0x5F, "LD E, A");

        opcodeMap.put(0x60, "LD H, B");
        opcodeMap.put(0x61, "LD H, C");
        opcodeMap.put(0x62, "LD H, D");
        opcodeMap.put(0x63, "LD H, E");
        opcodeMap.put(0x64, "LD H, H");
        opcodeMap.put(0x65, "LD H, L");
        opcodeMap.put(0x66, "LD H, (HL)");
        opcodeMap.put(0x67, "LD H, A");
        opcodeMap.put(0x68, "LD L, B");
        opcodeMap.put(0x69, "LD L, C");
        opcodeMap.put(0x6A, "LD L, D");
        opcodeMap.put(0x6B, "LD L, E");
        opcodeMap.put(0x6C, "LD L, H");
        opcodeMap.put(0x6D, "LD L, L");
        opcodeMap.put(0x6E, "LD L, (HL)");
        opcodeMap.put(0x6F, "LD L, A");

        opcodeMap.put(0x70, "LD (HL), B");
        opcodeMap.put(0x71, "LD (HL), C");
        opcodeMap.put(0x72, "LD (HL), D");
        opcodeMap.put(0x73, "LD (HL), E");
        opcodeMap.put(0x74, "LD (HL), H");
        opcodeMap.put(0x75, "LD (HL), L");
        opcodeMap.put(0x76, "HALT");
        opcodeMap.put(0x77, "LD (HL), A");
        opcodeMap.put(0x78, "LD A, B");
        opcodeMap.put(0x79, "LD A, C");
        opcodeMap.put(0x7A, "LD A, D");
        opcodeMap.put(0x7B, "LD A, E");
        opcodeMap.put(0x7C, "LD A, H");
        opcodeMap.put(0x7D, "LD A, L");
        opcodeMap.put(0x7E, "LD A, (HL)");
        opcodeMap.put(0x7F, "LD A, A");

        opcodeMap.put(0x80, "ADD A, B");
        opcodeMap.put(0x81, "ADD A, C");
        opcodeMap.put(0x82, "ADD A, D");
        opcodeMap.put(0x83, "ADD A, E");
        opcodeMap.put(0x84, "ADD A, H");
        opcodeMap.put(0x85, "ADD A, L");
        opcodeMap.put(0x86, "ADD A, (HL)");
        opcodeMap.put(0x87, "ADD A, A");
        opcodeMap.put(0x88, "ADC A, B");
        opcodeMap.put(0x89, "ADC A, C");
        opcodeMap.put(0x8A, "ADC A, D");
        opcodeMap.put(0x8B, "ADC A, E");
        opcodeMap.put(0x8C, "ADC A, H");
        opcodeMap.put(0x8D, "ADC A, L");
        opcodeMap.put(0x8E, "ADC A, (HL)");
        opcodeMap.put(0x8F, "ADC A, A");

        opcodeMap.put(0x90, "SUB A, B");
        opcodeMap.put(0x91, "SUB A, C");
        opcodeMap.put(0x92, "SUB A, D");
        opcodeMap.put(0x93, "SUB A, E");
        opcodeMap.put(0x94, "SUB A, H");
        opcodeMap.put(0x95, "SUB A, L");
        opcodeMap.put(0x96, "SUB A, (HL)");
        opcodeMap.put(0x97, "SUB A, A");
        opcodeMap.put(0x98, "SBC A, B");
        opcodeMap.put(0x99, "SBC A, C");
        opcodeMap.put(0x9A, "SBC A, D");
        opcodeMap.put(0x9B, "SBC A, E");
        opcodeMap.put(0x9C, "SBC A, H");
        opcodeMap.put(0x9D, "SBC A, L");
        opcodeMap.put(0x9E, "SBC A, (HL)");
        opcodeMap.put(0x9F, "SBC A, A");

        opcodeMap.put(0xA0, "AND A, B");
        opcodeMap.put(0xA1, "AND A, C");
        opcodeMap.put(0xA2, "AND A, D");
        opcodeMap.put(0xA3, "AND A, E");
        opcodeMap.put(0xA4, "AND A, H");
        opcodeMap.put(0xA5, "AND A, L");
        opcodeMap.put(0xA6, "AND A, (HL)");
        opcodeMap.put(0xA7, "AND A, A");
        opcodeMap.put(0xA8, "XOR A, B");
        opcodeMap.put(0xA9, "XOR A, C");
        opcodeMap.put(0xAA, "XOR A, D");
        opcodeMap.put(0xAB, "XOR A, E");
        opcodeMap.put(0xAC, "XOR A, H");
        opcodeMap.put(0xAD, "XOR A, L");
        opcodeMap.put(0xAE, "XOR A, (HL)");
        opcodeMap.put(0xAF, "XOR A, A");

        opcodeMap.put(0xB0, "OR A, B");
        opcodeMap.put(0xB1, "OR A, C");
        opcodeMap.put(0xB2, "OR A, D");
        opcodeMap.put(0xB3, "OR A, E");
        opcodeMap.put(0xB4, "OR A, H");
        opcodeMap.put(0xB5, "OR A, L");
        opcodeMap.put(0xB6, "OR A, (HL)");
        opcodeMap.put(0xB7, "OR A, A");
        opcodeMap.put(0xB8, "CP A, B");
        opcodeMap.put(0xB9, "CP A, C");
        opcodeMap.put(0xBA, "CP A, D");
        opcodeMap.put(0xBB, "CP A, E");
        opcodeMap.put(0xBC, "CP A, H");
        opcodeMap.put(0xBD, "CP A, L");
        opcodeMap.put(0xBE, "CP A, (HL)");
        opcodeMap.put(0xBF, "CP A, A");

        opcodeMap.put(0xC0, "RET NZ");
        opcodeMap.put(0xC1, "POP BC");
        opcodeMap.put(0xC2, "JP NZ, a16");
        opcodeMap.put(0xC3, "JP a16");
        opcodeMap.put(0xC4, "CALL NZ, a16");
        opcodeMap.put(0xC5, "PUSH BC");
        opcodeMap.put(0xC6, "ADD A, d8");
        opcodeMap.put(0xC7, "RST 0");
        opcodeMap.put(0xC8, "RET Z");
        opcodeMap.put(0xC9, "RET");
        opcodeMap.put(0xCA, "JP Z, a16");
        opcodeMap.put(0xCB, "#EXTENDED#");
        opcodeMap.put(0xCC, "CALL Z, a16");
        opcodeMap.put(0xCD, "CALL a16");
        opcodeMap.put(0xCE, "ADC A, d8");
        opcodeMap.put(0xCF, "RST 1");

        opcodeMap.put(0xD0, "RET NC");
        opcodeMap.put(0xD1, "POP DE");
        opcodeMap.put(0xD2, "JP NC, a16");
        opcodeMap.put(0xD3, "#UNIMPLEMENTED#");
        opcodeMap.put(0xD4, "CALL NC, a16");
        opcodeMap.put(0xD5, "PUSH DE");
        opcodeMap.put(0xD6, "SUB A, d8");
        opcodeMap.put(0xD7, "RST 2");
        opcodeMap.put(0xD8, "RET C");
        opcodeMap.put(0xD9, "RETI");
        opcodeMap.put(0xDA, "JP C, a16");
        opcodeMap.put(0xDB, "#UNIMPLEMENTED#");
        opcodeMap.put(0xDC, "CALL C, a16");
        opcodeMap.put(0xDD, "#UNIMPLEMENTED#");
        opcodeMap.put(0xDE, "SBC A, d8");
        opcodeMap.put(0xDF, "RST 3");

        opcodeMap.put(0xE0, "LD (a8), A");
        opcodeMap.put(0xE1, "POP HL");
        opcodeMap.put(0xE2, "LD (C), A");
        opcodeMap.put(0xE3, "#UNIMPLEMENTED#");
        opcodeMap.put(0xE4, "#UNIMPLEMENTED#");
        opcodeMap.put(0xE5, "PUSH HL");
        opcodeMap.put(0xE6, "AND A, d8");
        opcodeMap.put(0xE7, "RST 4");
        opcodeMap.put(0xE8, "ADD SP, s8");
        opcodeMap.put(0xE9, "JP HL");
        opcodeMap.put(0xEA, "LD (a16), A");
        opcodeMap.put(0xEB, "#UNIMPLEMENTED#");
        opcodeMap.put(0xEC, "#UNIMPLEMENTED#");
        opcodeMap.put(0xED, "#UNIMPLEMENTED#");
        opcodeMap.put(0xEE, "XOR A, d8");
        opcodeMap.put(0xEF, "RST 5");

        opcodeMap.put(0xF0, "LD A, (a8)");
        opcodeMap.put(0xF1, "POP AF");
        opcodeMap.put(0xF2, "LD A, (C)");
        opcodeMap.put(0xF3, "DI");
        opcodeMap.put(0xF4, "#UNIMPLEMENTED#");
        opcodeMap.put(0xF5, "PUSH AF");
        opcodeMap.put(0xF6, "OR A, d8");
        opcodeMap.put(0xF7, "RST 6");
        opcodeMap.put(0xF8, "LD HL, SP+s8");
        opcodeMap.put(0xF9, "LD SP, HL");
        opcodeMap.put(0xFA, "LD A, (a16)");
        opcodeMap.put(0xFB, "EI");
        opcodeMap.put(0xFC, "#UNIMPLEMENTED#");
        opcodeMap.put(0xFD, "#UNIMPLEMENTED#");
        opcodeMap.put(0xFE, "CP A, d8");
        opcodeMap.put(0xFF, "RST 7");

        opcodeMap.put(0xCB00, "RLC B");
        opcodeMap.put(0xCB01, "RLC C");
        opcodeMap.put(0xCB02, "RLC D");
        opcodeMap.put(0xCB03, "RLC E");
        opcodeMap.put(0xCB04, "RLC H");
        opcodeMap.put(0xCB05, "RLC L");
        opcodeMap.put(0xCB06, "RLC (HL)");
        opcodeMap.put(0xCB07, "RLC A");
        opcodeMap.put(0xCB08, "RRC B");
        opcodeMap.put(0xCB09, "RRC C");
        opcodeMap.put(0xCB0A, "RRC D");
        opcodeMap.put(0xCB0B, "RRC E");
        opcodeMap.put(0xCB0C, "RRC H");
        opcodeMap.put(0xCB0D, "RRC L");
        opcodeMap.put(0xCB0E, "RRC (HL)");
        opcodeMap.put(0xCB0F, "RRC A");

        opcodeMap.put(0xCB10, "RL B");
        opcodeMap.put(0xCB11, "RL C");
        opcodeMap.put(0xCB12, "RL D");
        opcodeMap.put(0xCB13, "RL E");
        opcodeMap.put(0xCB14, "RL H");
        opcodeMap.put(0xCB15, "RL L");
        opcodeMap.put(0xCB16, "RL (HL)");
        opcodeMap.put(0xCB17, "RL A");
        opcodeMap.put(0xCB18, "RR B");
        opcodeMap.put(0xCB19, "RR C");
        opcodeMap.put(0xCB1A, "RR D");
        opcodeMap.put(0xCB1B, "RR E");
        opcodeMap.put(0xCB1C, "RR H");
        opcodeMap.put(0xCB1D, "RR L");
        opcodeMap.put(0xCB1E, "RR (HL)");
        opcodeMap.put(0xCB1F, "RR A");

        opcodeMap.put(0xCB20, "SLA B");
        opcodeMap.put(0xCB21, "SLA C");
        opcodeMap.put(0xCB22, "SLA D");
        opcodeMap.put(0xCB23, "SLA E");
        opcodeMap.put(0xCB24, "SLA H");
        opcodeMap.put(0xCB25, "SLA L");
        opcodeMap.put(0xCB26, "SLA (HL)");
        opcodeMap.put(0xCB27, "SLA A");
        opcodeMap.put(0xCB28, "SRA B");
        opcodeMap.put(0xCB29, "SRA C");
        opcodeMap.put(0xCB2A, "SRA D");
        opcodeMap.put(0xCB2B, "SRA E");
        opcodeMap.put(0xCB2C, "SRA H");
        opcodeMap.put(0xCB2D, "SRA L");
        opcodeMap.put(0xCB2E, "SRA (HL)");
        opcodeMap.put(0xCB2F, "SRA A");

        opcodeMap.put(0xCB30, "SWAP B");
        opcodeMap.put(0xCB31, "SWAP C");
        opcodeMap.put(0xCB32, "SWAP D");
        opcodeMap.put(0xCB33, "SWAP E");
        opcodeMap.put(0xCB34, "SWAP H");
        opcodeMap.put(0xCB35, "SWAP L");
        opcodeMap.put(0xCB36, "SWAP (HL)");
        opcodeMap.put(0xCB37, "SWAP A");
        opcodeMap.put(0xCB38, "SRL B");
        opcodeMap.put(0xCB39, "SRL C");
        opcodeMap.put(0xCB3A, "SRL D");
        opcodeMap.put(0xCB3B, "SRL E");
        opcodeMap.put(0xCB3C, "SRL H");
        opcodeMap.put(0xCB3D, "SRL L");
        opcodeMap.put(0xCB3E, "SRL (HL)");
        opcodeMap.put(0xCB3F, "SRL A");

        opcodeMap.put(0xCB40, "BIT 0, B");
        opcodeMap.put(0xCB41, "BIT 0, C");
        opcodeMap.put(0xCB42, "BIT 0, D");
        opcodeMap.put(0xCB43, "BIT 0, E");
        opcodeMap.put(0xCB44, "BIT 0, H");
        opcodeMap.put(0xCB45, "BIT 0, L");
        opcodeMap.put(0xCB46, "BIT 0, (HL)");
        opcodeMap.put(0xCB47, "BIT 0, A");
        opcodeMap.put(0xCB48, "BIT 1, B");
        opcodeMap.put(0xCB49, "BIT 1, C");
        opcodeMap.put(0xCB4A, "BIT 1, D");
        opcodeMap.put(0xCB4B, "BIT 1, E");
        opcodeMap.put(0xCB4C, "BIT 1, H");
        opcodeMap.put(0xCB4D, "BIT 1, L");
        opcodeMap.put(0xCB4E, "BIT 1, (HL)");
        opcodeMap.put(0xCB4F, "BIT 1, A");

        opcodeMap.put(0xCB50, "BIT 2, B");
        opcodeMap.put(0xCB51, "BIT 2, C");
        opcodeMap.put(0xCB52, "BIT 2, D");
        opcodeMap.put(0xCB53, "BIT 2, E");
        opcodeMap.put(0xCB54, "BIT 2, H");
        opcodeMap.put(0xCB55, "BIT 2, L");
        opcodeMap.put(0xCB56, "BIT 2, (HL)");
        opcodeMap.put(0xCB57, "BIT 2, A");
        opcodeMap.put(0xCB58, "BIT 3, B");
        opcodeMap.put(0xCB59, "BIT 3, C");
        opcodeMap.put(0xCB5A, "BIT 3, D");
        opcodeMap.put(0xCB5B, "BIT 3, E");
        opcodeMap.put(0xCB5C, "BIT 3, H");
        opcodeMap.put(0xCB5D, "BIT 3, L");
        opcodeMap.put(0xCB5E, "BIT 3, (HL)");
        opcodeMap.put(0xCB5F, "BIT 3, A");

        opcodeMap.put(0xCB60, "BIT 4, B");
        opcodeMap.put(0xCB61, "BIT 4, C");
        opcodeMap.put(0xCB62, "BIT 4, D");
        opcodeMap.put(0xCB63, "BIT 4, E");
        opcodeMap.put(0xCB64, "BIT 4, H");
        opcodeMap.put(0xCB65, "BIT 4, L");
        opcodeMap.put(0xCB66, "BIT 4, (HL)");
        opcodeMap.put(0xCB67, "BIT 4, A");
        opcodeMap.put(0xCB68, "BIT 5, B");
        opcodeMap.put(0xCB69, "BIT 5, C");
        opcodeMap.put(0xCB6A, "BIT 5, D");
        opcodeMap.put(0xCB6B, "BIT 5, E");
        opcodeMap.put(0xCB6C, "BIT 5, H");
        opcodeMap.put(0xCB6D, "BIT 5, L");
        opcodeMap.put(0xCB6E, "BIT 5, (HL)");
        opcodeMap.put(0xCB6F, "BIT 5, A");

        opcodeMap.put(0xCB70, "BIT 6, B");
        opcodeMap.put(0xCB71, "BIT 6, C");
        opcodeMap.put(0xCB72, "BIT 6, D");
        opcodeMap.put(0xCB73, "BIT 6, E");
        opcodeMap.put(0xCB74, "BIT 6, H");
        opcodeMap.put(0xCB75, "BIT 6, L");
        opcodeMap.put(0xCB76, "BIT 6, (HL)");
        opcodeMap.put(0xCB77, "BIT 6, A");
        opcodeMap.put(0xCB78, "BIT 7, B");
        opcodeMap.put(0xCB79, "BIT 7, C");
        opcodeMap.put(0xCB7A, "BIT 7, D");
        opcodeMap.put(0xCB7B, "BIT 7, E");
        opcodeMap.put(0xCB7C, "BIT 7, H");
        opcodeMap.put(0xCB7D, "BIT 7, L");
        opcodeMap.put(0xCB7E, "BIT 7, (HL)");
        opcodeMap.put(0xCB7F, "BIT 7, A");

        opcodeMap.put(0xCB80, "RES 0, B");
        opcodeMap.put(0xCB81, "RES 0, C");
        opcodeMap.put(0xCB82, "RES 0, D");
        opcodeMap.put(0xCB83, "RES 0, E");
        opcodeMap.put(0xCB84, "RES 0, H");
        opcodeMap.put(0xCB85, "RES 0, L");
        opcodeMap.put(0xCB86, "RES 0, (HL)");
        opcodeMap.put(0xCB87, "RES 0, A");
        opcodeMap.put(0xCB88, "RES 1, B");
        opcodeMap.put(0xCB89, "RES 1, C");
        opcodeMap.put(0xCB8A, "RES 1, D");
        opcodeMap.put(0xCB8B, "RES 1, E");
        opcodeMap.put(0xCB8C, "RES 1, H");
        opcodeMap.put(0xCB8D, "RES 1, L");
        opcodeMap.put(0xCB8E, "RES 1, (HL)");
        opcodeMap.put(0xCB8F, "RES 1, A");

        opcodeMap.put(0xCB90, "RES 2, B");
        opcodeMap.put(0xCB91, "RES 2, C");
        opcodeMap.put(0xCB92, "RES 2, D");
        opcodeMap.put(0xCB93, "RES 2, E");
        opcodeMap.put(0xCB94, "RES 2, H");
        opcodeMap.put(0xCB95, "RES 2, L");
        opcodeMap.put(0xCB96, "RES 2, (HL)");
        opcodeMap.put(0xCB97, "RES 2, A");
        opcodeMap.put(0xCB98, "RES 3, B");
        opcodeMap.put(0xCB99, "RES 3, C");
        opcodeMap.put(0xCB9A, "RES 3, D");
        opcodeMap.put(0xCB9B, "RES 3, E");
        opcodeMap.put(0xCB9C, "RES 3, H");
        opcodeMap.put(0xCB9D, "RES 3, L");
        opcodeMap.put(0xCB9E, "RES 3, (HL)");
        opcodeMap.put(0xCB9F, "RES 3, A");

        opcodeMap.put(0xCBA0, "RES 4, B");
        opcodeMap.put(0xCBA1, "RES 4, C");
        opcodeMap.put(0xCBA2, "RES 4, D");
        opcodeMap.put(0xCBA3, "RES 4, E");
        opcodeMap.put(0xCBA4, "RES 4, H");
        opcodeMap.put(0xCBA5, "RES 4, L");
        opcodeMap.put(0xCBA6, "RES 4, (HL)");
        opcodeMap.put(0xCBA7, "RES 4, A");
        opcodeMap.put(0xCBA8, "RES 5, B");
        opcodeMap.put(0xCBA9, "RES 5, C");
        opcodeMap.put(0xCBAA, "RES 5, D");
        opcodeMap.put(0xCBAB, "RES 5, E");
        opcodeMap.put(0xCBAC, "RES 5, H");
        opcodeMap.put(0xCBAD, "RES 5, L");
        opcodeMap.put(0xCBAE, "RES 5, (HL)");
        opcodeMap.put(0xCBAF, "RES 5, A");

        opcodeMap.put(0xCBB0, "RES 6, B");
        opcodeMap.put(0xCBB1, "RES 6, C");
        opcodeMap.put(0xCBB2, "RES 6, D");
        opcodeMap.put(0xCBB3, "RES 6, E");
        opcodeMap.put(0xCBB4, "RES 6, H");
        opcodeMap.put(0xCBB5, "RES 6, L");
        opcodeMap.put(0xCBB6, "RES 6, (HL)");
        opcodeMap.put(0xCBB7, "RES 6, A");
        opcodeMap.put(0xCBB8, "RES 7, B");
        opcodeMap.put(0xCBB9, "RES 7, C");
        opcodeMap.put(0xCBBA, "RES 7, D");
        opcodeMap.put(0xCBBB, "RES 7, E");
        opcodeMap.put(0xCBBC, "RES 7, H");
        opcodeMap.put(0xCBBD, "RES 7, L");
        opcodeMap.put(0xCBBE, "RES 7, (HL)");
        opcodeMap.put(0xCBBF, "RES 7, A");

        opcodeMap.put(0xCBC0, "SET 0, B");
        opcodeMap.put(0xCBC1, "SET 0, C");
        opcodeMap.put(0xCBC2, "SET 0, D");
        opcodeMap.put(0xCBC3, "SET 0, E");
        opcodeMap.put(0xCBC4, "SET 0, H");
        opcodeMap.put(0xCBC5, "SET 0, L");
        opcodeMap.put(0xCBC6, "SET 0, (HL)");
        opcodeMap.put(0xCBC7, "SET 0, A");
        opcodeMap.put(0xCBC8, "SET 1, B");
        opcodeMap.put(0xCBC9, "SET 1, C");
        opcodeMap.put(0xCBCA, "SET 1, D");
        opcodeMap.put(0xCBCB, "SET 1, E");
        opcodeMap.put(0xCBCC, "SET 1, H");
        opcodeMap.put(0xCBCD, "SET 1, L");
        opcodeMap.put(0xCBCE, "SET 1, (HL)");
        opcodeMap.put(0xCBCF, "SET 1, A");

        opcodeMap.put(0xCBD0, "SET 2, B");
        opcodeMap.put(0xCBD1, "SET 2, C");
        opcodeMap.put(0xCBD2, "SET 2, D");
        opcodeMap.put(0xCBD3, "SET 2, E");
        opcodeMap.put(0xCBD4, "SET 2, H");
        opcodeMap.put(0xCBD5, "SET 2, L");
        opcodeMap.put(0xCBD6, "SET 2, (HL)");
        opcodeMap.put(0xCBD7, "SET 2, A");
        opcodeMap.put(0xCBD8, "SET 3, B");
        opcodeMap.put(0xCBD9, "SET 3, C");
        opcodeMap.put(0xCBDA, "SET 3, D");
        opcodeMap.put(0xCBDB, "SET 3, E");
        opcodeMap.put(0xCBDC, "SET 3, H");
        opcodeMap.put(0xCBDD, "SET 3, L");
        opcodeMap.put(0xCBDE, "SET 3, (HL)");
        opcodeMap.put(0xCBDF, "SET 3, A");

        opcodeMap.put(0xCBE0, "SET 4, B");
        opcodeMap.put(0xCBE1, "SET 4, C");
        opcodeMap.put(0xCBE2, "SET 4, D");
        opcodeMap.put(0xCBE3, "SET 4, E");
        opcodeMap.put(0xCBE4, "SET 4, H");
        opcodeMap.put(0xCBE5, "SET 4, L");
        opcodeMap.put(0xCBE6, "SET 4, (HL)");
        opcodeMap.put(0xCBE7, "SET 4, A");
        opcodeMap.put(0xCBE8, "SET 5, B");
        opcodeMap.put(0xCBE9, "SET 5, C");
        opcodeMap.put(0xCBEA, "SET 5, D");
        opcodeMap.put(0xCBEB, "SET 5, E");
        opcodeMap.put(0xCBEC, "SET 5, H");
        opcodeMap.put(0xCBED, "SET 5, L");
        opcodeMap.put(0xCBEE, "SET 5, (HL)");
        opcodeMap.put(0xCBEF, "SET 5, A");

        opcodeMap.put(0xCBF0, "SET 6, B");
        opcodeMap.put(0xCBF1, "SET 6, C");
        opcodeMap.put(0xCBF2, "SET 6, D");
        opcodeMap.put(0xCBF3, "SET 6, E");
        opcodeMap.put(0xCBF4, "SET 6, H");
        opcodeMap.put(0xCBF5, "SET 6, L");
        opcodeMap.put(0xCBF6, "SET 6, (HL)");
        opcodeMap.put(0xCBF7, "SET 6, A");
        opcodeMap.put(0xCBF8, "SET 7, B");
        opcodeMap.put(0xCBF9, "SET 7, C");
        opcodeMap.put(0xCBFA, "SET 7, D");
        opcodeMap.put(0xCBFB, "SET 7, E");
        opcodeMap.put(0xCBFC, "SET 7, H");
        opcodeMap.put(0xCBFD, "SET 7, L");
        opcodeMap.put(0xCBFE, "SET 7, (HL)");
        opcodeMap.put(0xCBFF, "SET 7, A");

        return opcodeMap;
    }
}
